// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.8.0
// source: base/network/grpc/grpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_network_grpc_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_base_network_grpc_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_base_network_grpc_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_base_network_grpc_grpc_proto protoreflect.FileDescriptor

var file_base_network_grpc_grpc_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x67, 0x72, 0x70, 0x63, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x3a, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_base_network_grpc_grpc_proto_rawDescOnce sync.Once
	file_base_network_grpc_grpc_proto_rawDescData = file_base_network_grpc_grpc_proto_rawDesc
)

func file_base_network_grpc_grpc_proto_rawDescGZIP() []byte {
	file_base_network_grpc_grpc_proto_rawDescOnce.Do(func() {
		file_base_network_grpc_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_network_grpc_grpc_proto_rawDescData)
	})
	return file_base_network_grpc_grpc_proto_rawDescData
}

var file_base_network_grpc_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_base_network_grpc_grpc_proto_goTypes = []interface{}{
	(*Message)(nil), // 0: grpc.Message
}
var file_base_network_grpc_grpc_proto_depIdxs = []int32{
	0, // 0: grpc.Communicate.Connect:input_type -> grpc.Message
	0, // 1: grpc.Communicate.Connect:output_type -> grpc.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_base_network_grpc_grpc_proto_init() }
func file_base_network_grpc_grpc_proto_init() {
	if File_base_network_grpc_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_network_grpc_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_network_grpc_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_base_network_grpc_grpc_proto_goTypes,
		DependencyIndexes: file_base_network_grpc_grpc_proto_depIdxs,
		MessageInfos:      file_base_network_grpc_grpc_proto_msgTypes,
	}.Build()
	File_base_network_grpc_grpc_proto = out.File
	file_base_network_grpc_grpc_proto_rawDesc = nil
	file_base_network_grpc_grpc_proto_goTypes = nil
	file_base_network_grpc_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CommunicateClient is the client API for Communicate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommunicateClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Communicate_ConnectClient, error)
}

type communicateClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicateClient(cc grpc.ClientConnInterface) CommunicateClient {
	return &communicateClient{cc}
}

func (c *communicateClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Communicate_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Communicate_serviceDesc.Streams[0], "/grpc.Communicate/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &communicateConnectClient{stream}
	return x, nil
}

type Communicate_ConnectClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type communicateConnectClient struct {
	grpc.ClientStream
}

func (x *communicateConnectClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *communicateConnectClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommunicateServer is the server API for Communicate service.
type CommunicateServer interface {
	Connect(Communicate_ConnectServer) error
}

// UnimplementedCommunicateServer can be embedded to have forward compatible implementations.
type UnimplementedCommunicateServer struct {
}

func (*UnimplementedCommunicateServer) Connect(Communicate_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func RegisterCommunicateServer(s *grpc.Server, srv CommunicateServer) {
	s.RegisterService(&_Communicate_serviceDesc, srv)
}

func _Communicate_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommunicateServer).Connect(&communicateConnectServer{stream})
}

type Communicate_ConnectServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type communicateConnectServer struct {
	grpc.ServerStream
}

func (x *communicateConnectServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *communicateConnectServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Communicate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Communicate",
	HandlerType: (*CommunicateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Communicate_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "base/network/grpc/grpc.proto",
}
